[package]
name = "type-aliasing-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    ".",
    "foo",
]

[dev-dependencies]
foo = { path = "foo" }